### ISSUE TITLE
Commit Dialog window crashes

### ISSUE THREAD

**Issue by ajmaske** [nemwiz/jira-commit-message-intellij-plugin#55]
**Describe the bug**
When opening the commit dialog window to test a commit, the dialog window crashes and doesn't open.

**To Reproduce**
1. Installed v3.0.1 of the plugin from the JetBrains Plugin Library
2. Configured several Jira ID's
3. Changed a file
4. Click the commit button
5. Crash

**Expected behavior**
Commit window should open as normal

**Stack Trace**
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.intellij.util.SmartList.checkOutOfBounds(SmartList.java:70)
	at com.intellij.util.SmartList.get(SmartList.java:61)
	at org.nemwiz.jiracommitmessage.services.MyProjectService.getTaskIdFromBranchName(MyProjectService.kt:39)
	at org.nemwiz.jiracommitmessage.provider.PluginProvider.getCommitMessage(PluginProvider.kt:13)
	at com.intellij.vcs.commit.AbstractCommitMessagePolicy.getCommitMessageFor(AbstractCommitMessagePolicy.kt:24)
	at com.intellij.vcs.commit.SingleChangeListCommitMessagePolicy.init(SingleChangeListCommitMessagePolicy.kt:28)
	at com.intellij.vcs.commit.SingleChangeListCommitWorkflowHandler.initCommitMessage(SingleChangeListCommitWorkflowHandler.kt:113)
	at com.intellij.vcs.commit.SingleChangeListCommitWorkflowHandler.activate(SingleChangeListCommitWorkflowHandler.kt:54)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:224)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:142)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCheckIn(CheckinActionUtil.kt:121)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCheckInAfterUpdate$lambda$1(CheckinActionUtil.kt:87)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$CallbackBase.invokeCallback(InvokeAfterUpdateCallback.java:66)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$ProgressCallback$ModalWaiter.onFinished(InvokeAfterUpdateCallback.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$10(CoreProgressManager.java:528)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:408)
	at com.intellij.openapi.application.ex.ApplicationUtil.invokeAndWaitSomewhere(ApplicationUtil.java:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:369)
	at com.intellij.openapi.progress.Task.queue(Task.java:119)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$ProgressCallback.startProgress(InvokeAfterUpdateCallback.java:127)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue.invokeAfterUpdate(UpdateRequestsQueue.java:181)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:368)
	at com.intellij.openapi.vcs.changes.ChangeListManager.invokeAfterUpdateWithModal(ChangeListManager.java:75)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCheckInAfterUpdate(CheckinActionUtil.kt:85)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCommonCommitAction(CheckinActionUtil.kt:71)
	at com.intellij.openapi.vcs.actions.commit.CommonCheckinProjectActionKt.performCheckinProjectAction(CommonCheckinProjectAction.kt:118)
	at com.intellij.openapi.vcs.actions.commit.CommonCheckinProjectActionKt.access$performCheckinProjectAction(CommonCheckinProjectAction.kt:1)
	at com.intellij.openapi.vcs.actions.commit.CommonCheckinProjectAction.actionPerformed(CommonCheckinProjectAction.kt:65)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:197)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**System version (please complete the following information):**
 - IntelliJ version: 2022.3.1
 - Plugin version: 3.0.1
 - OS: Windows 10

**Additional context**

**Comment by nemwiz** [comment]
I wasn't able to re-produce this bug. It fails on the below code and I suspect that something about your Git repository is not configured since the repositories list is empty. 
Could you double check that IntelliJ knows about your repository? You can find some of these options in the settings under "Git" or "Github" depending on what you are using.

It would be great if you could share those settings here as well so that I can try to re-produce and improve the error handling.

```kotlin
val repositoryManager = getRepositoryManager(project)
val branch = repositoryManager.repositories[0].currentBranch
```

**Comment by nemwiz** [comment]
@ajmaske Any update on this? Would be great if we can tackle this bug, but I need more info in order to re-produce it.

**Comment by ajmaske** [comment]
Sorry, just saw your reply from 2 weeks ago.  We're not using GIT, we're using Subversion.  I'm assuming that the plugin doesn't work with subversion?

**Comment by nemwiz** [comment]
Yes, you are right the plugin only works with Git. In general, I wouldn't mind supporting multiple options but Subversion usage has been in constant decline and it's not an industry standard anymore. Github also announced recently that they [will stop supporting Subversion](https://github.blog/2023-01-20-sunsetting-subversion-support/)
Considering all these things, it doesn't make sense to add Subversion support for the plugin.
