### ISSUE TITLE
Trying to commit produce an IDE error (SVN versioned)

### ISSUE THREAD

**Issue by YaelBx** [nemwiz/jira-commit-message-intellij-plugin#65]
**Trying to commit produce an IDE error (SVN versioned)**
I tried to use this plugin with my projects (which are SVN - Subversion versioned), and trying to commit any file generates an IDE error without displaying the commit window.

**To Reproduce**
1. Open my project (which is versioned through SVN - Subversion)
2. Click on Subversion tab
3. Click on any file
4. Click on 'Commit file...'

**Expected behavior**
The commit window appear

**Observed  behavior**
An IDE error occurs

**Screenshots**
![2023-03-10_09h15_07](https://user-images.githubusercontent.com/32430832/224260812-21ec0794-e183-4e25-b935-93ac9e75d655.png)
![2023-03-10_09h15_21](https://user-images.githubusercontent.com/32430832/224260874-cb4a3559-91d3-4310-8a9f-d0481a6b8fb3.png)

Stacktrace :
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.intellij.util.SmartList.checkOutOfBounds(SmartList.java:70)
	at com.intellij.util.SmartList.get(SmartList.java:61)
	at org.nemwiz.jiracommitmessage.provider.PluginProvider.getCommitMessage(PluginProvider.kt:17)
	at com.intellij.vcs.commit.AbstractCommitMessagePolicy.getCommitMessageFor(AbstractCommitMessagePolicy.kt:24)
	at com.intellij.vcs.commit.SingleChangeListCommitMessagePolicy.init(SingleChangeListCommitMessagePolicy.kt:28)
	at com.intellij.vcs.commit.SingleChangeListCommitWorkflowHandler.initCommitMessage(SingleChangeListCommitWorkflowHandler.kt:113)
	at com.intellij.vcs.commit.SingleChangeListCommitWorkflowHandler.activate(SingleChangeListCommitWorkflowHandler.kt:54)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:224)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:142)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCheckIn(CheckinActionUtil.kt:121)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCheckInAfterUpdate$lambda$1(CheckinActionUtil.kt:87)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$CallbackBase.invokeCallback(InvokeAfterUpdateCallback.java:66)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$ProgressCallback$ModalWaiter.onFinished(InvokeAfterUpdateCallback.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$10(CoreProgressManager.java:534)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:433)
	at com.intellij.openapi.application.ex.ApplicationUtil.invokeAndWaitSomewhere(ApplicationUtil.java:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:367)
	at com.intellij.openapi.progress.Task.queue(Task.java:119)
	at com.intellij.openapi.vcs.changes.InvokeAfterUpdateCallback$ProgressCallback.startProgress(InvokeAfterUpdateCallback.java:127)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue.invokeAfterUpdate(UpdateRequestsQueue.java:181)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:368)
	at com.intellij.openapi.vcs.changes.ChangeListManager.invokeAfterUpdateWithModal(ChangeListManager.java:75)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCheckInAfterUpdate(CheckinActionUtil.kt:85)
	at com.intellij.openapi.vcs.actions.commit.CheckinActionUtil.performCommonCommitAction(CheckinActionUtil.kt:71)
	at com.intellij.openapi.vcs.actions.commit.CommonCheckinFilesAction.actionPerformed(CommonCheckinFilesAction.kt:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:289)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:64)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**System version (please complete the following information):**
 - CLion version: 2022.3.2, Build #CL-223.8617.54, built on January 25, 2023
 - Plugin version: 3.2.0
 - OS: Windows 10

**Additional context**
I am trying the manual mode of the plugin (lets say it has the XYZ label)
- the SVN link is https://xxxxxxxxxx/xxx/xxxxxxx/sandbox/XYZ-295_xxx_xxxx_xxxx_xxxxxxxx
- the local folder is D:\xxxxx\xxxx\sbx\XYZ-295_xx_xxx

**Comment by nemwiz** [comment]
Hi @YaelBx,
Thank you for reporting this issue. Unfortunately, this plugin only works with Git and there are no plans to support Subversion. In one of [the previous issues](https://github.com/nemwiz/jira-commit-message-intellij-plugin/issues/55), I've provided reasoning on this decision.

**Comment by YaelBx** [comment]
Hi @nemwiz,
I fully understand this decision and this is what I supposed. It would be really nice that this information figures early in the README.md, like

_A simple plugin that takes JIRA issue from your branch name and appends it to the commit message. Supports both commit dialog and commit tool window. Supports only git versioning system._ This might spare some time for developer working on non-git versioning systems.

For my personal case, since I have now the information, I close as "Won't fix" this ticket.

Have a great day !

**Comment by nemwiz** [comment]
Thanks for your feedback and I fully agree with you, this should be written down. I've [updated the plugin description](https://github.com/nemwiz/jira-commit-message-intellij-plugin/pull/66/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and added a disclaimer that the plugin only supports Git.
